### ISSUE TITLE
Middle-click doesn't remove the redirects

### ISSUE THREAD

**Issue by brunolopes96** [matagus/remove-google-redirects-addon#18]
If a webpage link from Google results is opened in a new tab (middle-click on link) it still opens the website with the redirector. To remove the redirector it's needed to click with left or right first.

**Comment by matagus** [comment]
Hi @brunolopes96:

Thanks for reporting this issue. 

As far as I tested -[current published version from AMO](https://addons.mozilla.org/en-US/firefox/addon/google-no-tracking-url/)- it works perfect. You must notice what I warn in the description of the addon:

> How it works (and why it works that way)

> When I first developed this addon, it worked by changing every single link in every google search result page you load. This is quite expensive (for the browser) and in some cases (like Google Image Search when you scroll down several times and that loads a lot of images) the browser performance get downgraded.

> So the addon does not modifies every google search results links in a page anymore: it waits till you click one of them (left, right or middle button click) or till you open a new tab and paste an url in the url bar: then the addon intercepts the network request (if it is a google redirect) and fixes it and does the request to the final url.

> It's a little complex and not intuitive, but I've found that this is the way to go. Other addons fail when you paste a google result link with a redirect because they only work when you click on it or when you copy it.

That is what -I think, please show if I'm wrong- you're seeing: the new tab gets opened with the google redirect link but the addon cancels the request before it starts and starts a new request to the right link.

Hope it helps. If you think it's not that way, please tell me:

 * What version of Firefox are you using?
 * Which operating system and version? 
 * Do you have any other addons installed? Please list them all (it's important since other addons could be interfering with this addon -or the other way around-) so I can try to reproduce the issue.

**Comment by brunolopes96** [comment]
> ... the new tab gets opened with the Google redirect link but the addon cancels the request before it starts and starts a new request to the right link.

Well, it is working that way, however the page links on Google's results page isn't corrected if middle-clicked.

Here's a GIF showing the steps (pay attention in the bottom-left corner address tooltip):
![steps](https://cloud.githubusercontent.com/assets/5515856/8537809/63f97934-243a-11e5-8d31-49e7d93b5812.gif)

Sorry, the longest note appears too fast, it says: "Middle-clicking, Google puts the redirection, and right after, Remove-Google-Redirects should correct the link".

Firefox 39.0
Windows 7
[Extensions](http://pastebin.com/A2kAqT7x)

**Comment by matagus** [comment]
Good to know it's working :)

Yes, like you noticed, the links aren't fixed when middle-clicked in the current version (1.3.1) but there's a fix coming in the [next version (1.4.0) that it's waiting for review in AMO](https://addons.mozilla.org/en-US/firefox/addon/google-no-tracking-url/versions/).

(Just for internal use: already reported at #14)
